fix: run on node16
codespell-project/actions-codespell pull request #51
Opened 2022-10-11 09:08 UTC by edwardgronroos

Since node-12 is now unsupported, GitHub will run all actions on node-16 instead.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Using this action currently gives this warning:
![image](https://user-images.githubusercontent.com/254408/195039854-65f17574-a9a4-4f6a-94ea-52a99107cb58.png)

2022-10-11 14:45 UTC, peternewman requested changes
Thanks @edwardgronroos , although I don't see the annotation on our test run, and that folder's action.yml isn't the one for the actual action.

Would you mind fixing that upstream in https://github.com/codespell-project/codespell-problem-matcher and then updating the git submodule please.

You could also do our sort one too if you're feeling keen?
https://github.com/codespell-project/sort-problem-matcher

I can confirm we do see it at least on the latter:
https://github.com/codespell-project/codespell/actions/runs/3224764715

I'm also a bit surprised you're just using our codespell problem matcher action, rather than just using the codespell action directly.

2022-10-12 08:58 UTC, edwardgronroos commented
My mistake, where a bit too quick pointing here. We're using the codespell action directly, but where referencing the hash right before the action upgrade one.

Will create PRs for the matchers and update the submodule in this one.

2022-10-12 09:41 UTC, peternewman commented
> We're using the codespell action directly, but where referencing the hash right before the action upgrade one.

Can I ask why if you don't mind?

> Will create PRs for the matchers and update the submodule in this one.

Thanks, much appreciated!

2022-10-12 11:43 UTC, closed without merging

2022-10-12 12:10 UTC, edwardgronroos commented
We are whitelisting all actions by SHA instead of tags/version from security perspective.
Guess on the time of whitelisting that it where the latest available version.

The reference to the submodule upstream got lost when I forked, so couldn't assist on updating it and thus closed this PR.

Thanks for a great action that saved med from shipping many typos 😅